### ISSUE TITLE
[Feature Request]: Remove the Black Overlay on Search Box Popup

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI_frontend#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A setting to remove the overlay for the popup searching box. 

### Proposed workflow

1. open settings
2. tweak settings that we do not want enforced
3. post more feature requests

**Comment by christian-byrne** [comment]
You can change it in `ComfyUI/web/user.css`:

```css
.node-search-box-dialog-mask {
  background-color: transparent !important;
}
```
