### ISSUE TITLE
[Bug]: `Workspce.SearchBox.Toggle` does not respect `Comfy.NodeSearchBoxImpl`

### ISSUE THREAD

**Issue by dbeecham** [Comfy-Org/ComfyUI_frontend#4122]
### Custom Node Testing

- [x] I have tried disabling custom nodes and the issue persists (see [how to disable custom nodes](https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled) if you need help)

### Frontend Version

1.21.7

### Expected Behavior

Litegraph search box appears.

### Actual Behavior

Default search box appears.

### Steps to Reproduce

Bind some button to `Toggle Search Box`, set `Node search box implementation` to `litegraph`. Hit the button.

### Debug Logs

```powershell
Nothing interesting.
```

### Browser Logs

Nothing interesting.

### Setting JSON

Basically this (file is on another machine)

```
Comfy.TutorialCompleted: true
Comfy.Keybinding.NewBindings:
  Comfy.SearchBox.Toggle: a
  Comfy.Manager.CustomNodesManager: Shift + N
  Comfy.GroupNode.ConvertSelectedNodesToGroupNode: Shift + G
  Workspace.NextOpenedWorkflow: Alt + Tab
  Workspace.PreviousOpenedWorkflow: Shift + Alt + Tab
Comfy.Keybinding.UnsetBindings:
  Comfy.GroupNode.ConvertSelectedNodesToGroupNode: Alt + G
Comfy.NodeSearchBoxImpl: default
Comfy.DevMode: true
Comfy.NodeSuggestions.number: 10 (does not work either, but that's ok)
```

### What browsers do you use to access the UI ?

Google Chrome
